[package]
name = "gb-desktop"
description = "Frontend gráfico: janela, teclado e áudio."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gb-core = { path = "../gb-core" }
winit = "0.28"
pixels = "0.13"
cpal = "0.15"
